### ISSUE TITLE
Bug: Using embedProject causes polluted history in Firefox

### ISSUE THREAD

**Issue by Chalks** [stackblitz/sdk#10]
### The Problem

Every time I call `embedProject` my browser history gets another instance of the current page in it:

<img width="893" alt="Screen Shot 2023-07-16 at 2 42 22 PM" src="https://github.com/stackblitz/sdk/assets/6187555/3485b3c8-0dd0-49ec-ad6f-cc13c8316f76">

### Causes?

I believe this is being caused by https://github.com/stackblitz/sdk/blob/main/src/lib.ts#L65 because `write` can do fun things [according to the documentation](https://developer.mozilla.org/en-US/docs/Web/API/Document/write) which states:

> Note: Because document.write() writes to the document stream, calling document.write() on a closed (loaded) document automatically calls document.open(), [which will clear the document](https://developer.mozilla.org/en-US/docs/Web/API/Document/open#notes).

I'm pretty sure that's where the issue stems from, but I'm not 100% sure.

### How to reproduce

You can clone https://github.com/Chalks/stackblitz-issue and run `npm run dev`. Follow the instructions in the readme to see the issue. I've reproduced this in Firefox on an m1 mac, but not in Chrome.

The embedded component is [here](https://github.com/Chalks/stackblitz-issue/blob/main/src/components/StackblitzEmbed.vue)

The page it's included on is [here](https://github.com/Chalks/stackblitz-issue/blob/main/src/pages/bug.vue)

---

I hope I'm just using the SDK incorrectly, but this seems like the "right" way to do it, and this issue is a complete non-starter for me.

**Comment by kamranayub** [comment]
I'm testing this out within Docusaurus, and in Firefox 119 and I don't see this issue. We just have a simple HTML page being displayed. Maybe Vue is messing with the routing?

**Comment by Chalks** [comment]
Thanks for looking @kamranayub. I just now got back around to looking at this, and as of today, the issue no longer occurs, even in my reproduce repo. The underlying dependencies haven't changed afaik, so best as I can tell is that this is something Firefox changed internally.

Well, at least I can stop worrying about it.  :|
